### PR TITLE
Fix tos_on_public_shares

### LINKED ISSUE #471: Possible mistake on "tos_on_public_shares" handling
@nickvergessen @LukasReschke 

https://github.com/nextcloud/terms_of_service/blob/6d9465b5ae24871a68efb3ae72c4ef8a6e2d6d85/lib/Filesystem/Helper.php#L101
It seems the access verification is always successful when `tos_on_public_shares` app config is disabled. Even for files that are not related to any public share.
Is it really the expected behaviour?

I made a few tests and DAV requests are indeed never blocked by this app if `tos_on_public_shares` is different than '1'.

### PR DESCRIPTION
**Pull request by eneiluj**
These are the same changes as in #491 but on master branch.

@daita I confirm it works now! ToS check is done correctly for normal files (not the public shares), whatever the `tos_on_public_shares` value.

fixes #471

### CODE REVIEW

**Comment by daita** [comment]
Thanks for the rebase <3

File: lib/Filesystem/Helper.php [hunk 1]
```diff
@@ -98,8 +98,7 @@ protected function isBlockable(string $path): bool {
 
 	public function verifyAccess(string $path): bool {
 		$config = OC::$server->getConfig();
```
Comment (daita) [inline lib/Filesystem/Helper.php:100]: you can also dismiss this creation of $config

**Review by daita — CHANGES_REQUESTED** [review]

File: lib/Filesystem/Helper.php (hunk 1 above)
Comment (eneiluj) [reply lib/Filesystem/Helper.php]: Oops, nice catch. Done.

**Comment by eneiluj** [comment]
@daita Is it ready to be merged now?

**Comment by daita** [comment]
@nickvergessen is not fully available right now :(

**Comment by eneiluj** [comment]
And I had forgotten to ask for his review... :grin:

**Review by nickvergessen — APPROVED** [review]

**Comment by nickvergessen** [comment]
Rebased due to conflicts on the use-block in Helper.php

**Comment by nickvergessen** [comment]
Backport to X?
